#!/bin/bash
VERSION_CONTROLLER='GIT'
CICD_AUTOMATION='JENKINS'
CONTAINER_TECHNOLOGY='DOCKER'
ORCHESTRATION_TOOL='KUBERNETES'
CONFIGURATION_TOOL='ANSIBLE'
LOGGING='EFK'
OBSERVABILITY='PROMETHUES AND GRAFANA'

echo $VERSION_CONTROLLER
echo $CICD_AUTOMATION
echo $CONTAINER_TECHNOLOGY
echo $ORCHESTRATION_TOOL
echo $CONFIGURATION_TOOL
echo $LOGGING
echo "$OBSERVABILITY"